### ISSUE TITLE
Reg: Saving Edits and building a fasta file

### ISSUE THREAD

**Issue by harish0201** [wtsi-hpag/PretextView#1]
Hi,

Thanks for developing a really amazing tool! I can easily load maps to visualize and quickly review the edits that might be needed.

However, I'm curious if I can save the edits, and build out the fasta sequence of the now modified assembly so as to have a quick save between each edit session.

On a similar note, since the changes made can be copied to a clipboard and hence to a file, would it be possible to build a new map from the same?

**Comment by EdHarry** [comment]
Hi, 

Thank you for your interest in Pretext.

Unfortunately there is currently no direct way to export the edits as a fasta file, since the map is divorced from the original sequence.

I would also advise caution in relying on HiC only when manually editing scaffolds or contigs, as the resolution is usually on the 100s of Kbp level, and the HiC signals can sometimes be misleading.

However, if you make a manual note the the edits, or use the GUI button to copy to the clipboard, you could  then use an assembly editing tool, such as gap5 https://www.sanger.ac.uk/science/tools/gap5, ideally along with some mapped long reads to really see if the edits look plausible.

**Comment by harish0201** [comment]
Damn. I was dreading this answer because PretextView makes things really
easy to visualize (I have astigmatism) using various color profiles and is
pretty lightweight to boot.

I'll check out gap5, but would it be possible to create something akin to a
bed formatted file that can easily used to export and visit the changes
back again?

I'd be really happy if you could add this support downstream sometime :)

**Comment by EdHarry** [comment]
I could perhaps add a feature to export the edits as an AGP file. I’ll have to have a think about the best way to implement that.

Also, due to the Covid lockdown I am away from my usual dev setup, so you may have to bear with me while I get setup at home. I also don’t have easy access to a Windows machine at home, so I may not be able to release a new Windows version before the end of the lockdown.

**Comment by harish0201** [comment]
No problem, please take your time. I work on a Linux station exclusively,
so it should be fine.

**Comment by harish0201** [comment]
Hi, 

There's also another thing, that I just noticed, might be particularity to my system only. 

System config:
![image](https://user-images.githubusercontent.com/9093815/80276241-fc41a180-8704-11ea-9dca-140500f739fc.png)

Whenever I zoom, it seems that there is a global zoom on the map, i.e the center of the Map is what gets zoomed all over. This should be a function, where the user selects a block, then that portion zooms in.

**Comment by EdHarry** [comment]
> Hi,
> 
> There's also another thing, that I just noticed, might be particularity to my system only.
> 
> System config:
> ![image](https://user-images.githubusercontent.com/9093815/80276241-fc41a180-8704-11ea-9dca-140500f739fc.png)
> 
> Whenever I zoom, it seems that there is a global zoom on the map, i.e the center of the Map is what gets zoomed all over. This should be a function, where the user selects a block, then that portion zooms in.

Sorry, I don't quite understand what you mean.  When you scroll the camera should zoom into whatever is currently centred. Is this not happening? Or is this not what you want to happen?

**Comment by harish0201** [comment]
Hi,

I think you got it correct the first time. That is what I'm expecting to
happen, but it doesn't.

**Comment by EdHarry** [comment]
> Hi,
> 
> I think you got it correct the first time. That is what I'm expecting to
> happen, but it doesn't.

Oh, that's strange. Does the camera pan back to the centre of the map when you scroll?

**Comment by harish0201** [comment]
Yup! I'll see how to create a screen recording so that I can better show it.

Thank you for all the help!

**Comment by harish0201** [comment]
Hi!

Thank you implementing this! Unfortunately, I'm not really working in this domain (genome assemblies etc) these days, so I don't have any datasets on hand.

I'll let you know whenever I do get a chance to test this though!
